export enum ActionTypeKeys {
    SET_USER = "SET_USER",
    SET_REPOSITORIES = "SET_REPOSITORIES",
    SET_LANGUAGE_STATISTICS = "SET_LANGUAGE_STATISTICS",
    SORT_REPOSITORIES = "SORT_REPOSITORIES",
    OTHER_ACTION = "__any_other_action_type__"
}