export type User = {
  login: string,
  name: string,
  bio: string,
  location: string,
  company: string,
  blog: string,
  email: string,
  avatar_url: string,
  html_url: string,
  public_repos: number,
  public_gists: number,
  followers: number,
  following: number,
  repos_url: string,
};
